apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-tv-library
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-tv-library
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-movie-library
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-movie-library
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi