apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/config/bazarr"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-tv-library
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/library/tv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-movie-library
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/library/movies"