apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/config/overseerr"
