apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: overseerr
spec:
  rules:
  - host: overseerr.arloz.dahan.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              name: webui
