apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-tv-data
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-tv-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-movie-data
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-movie-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi