apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: sonarr
spec:
  rules:
  - host: sonarr.home.amitd.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              name: webui