apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/config/sonarr"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-downloads
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/downloads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-library
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/library/tv"