apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/config/transmission"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-pv-downloads
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/downloads"