apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: transmission-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc-downloads
  namespace: media
spec:
  storageClassName: manual
  volumeName: transmission-pv-downloads
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi