apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-pv-data
  namespace: finance
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/t5/config/actual"