---
version: "3.8"

services:
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/emby:/config
      - ${DATA_PATH}/library/tv:/data/tvshows
      - ${DATA_PATH}/library/movies:/data/movies
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - 9096:8096
    devices:
      - /dev/dri:/dev/dri
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8096
      interval: 10s
      timeout: 5s
      retries: 5

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/jellyfin:/config
      - ${DATA_PATH}/library/tv:/data/tvshows
      - ${DATA_PATH}/library/movies:/data/movies
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/vcsm-cma:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8096
      interval: 10s
      timeout: 5s
      retries: 5

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${DATA_PATH}/config/plex:/config
      - ${DATA_PATH}/library/tv:/tv
      - ${DATA_PATH}/library/movies:/movies
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:32400/web/index.html
      interval: 10s
      timeout: 5s
      retries: 5

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/sonarr:/config
      - ${DATA_PATH}/library/tv:/tv
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    healthcheck:
      test: curl -f http://localhost:8989
      interval: 10s
      timeout: 5s
      retries: 5

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/radarr:/config
      - ${DATA_PATH}/library/movies:/movies
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:7878
      interval: 10s
      timeout: 5s
      retries: 5

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - AUTO_UPDATE=true
    volumes:
      - ${DATA_PATH}/config/jakett:/config
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9117
      interval: 10s
      timeout: 5s
      retries: 5

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/transmission:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9091/transmission/web/
      interval: 10s
      timeout: 5s
      retries: 5
