---
version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5454:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ${DATA_PATH}/config/plex:/config
      - ${DATA_PATH}/library/tv:/tv
      - ${DATA_PATH}/library/movies:/movies
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:32400/web/index.html
      interval: 10s
      timeout: 5s
      retries: 5

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/sonarr:/config
      - ${DATA_PATH}/library/tv:/tv
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8989
      interval: 10s
      timeout: 5s
      retries: 5

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/radarr:/config
      - ${DATA_PATH}/library/movies:/movies
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:7878
      interval: 10s
      timeout: 5s
      retries: 5

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - AUTO_UPDATE=true
    volumes:
      - ${DATA_PATH}/config/jackett:/config
      - ${DATA_PATH}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9117
      interval: 10s
      timeout: 5s
      retries: 5

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${DATA_PATH}/config/transmission:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9091/transmission/web/
      interval: 10s
      timeout: 5s
      retries: 5
