apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawdbot-pvc-config
  namespace: smart-home
spec:
  storageClassName: manual
  volumeName: clawdbot-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
