apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc-config
  namespace: smart-home
spec:
  storageClassName: manual
  volumeName: mosquitto-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
